version: '3.9'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=legacy
      - POSTGRES_PASSWORD=legacy
    ports:
      - "5432:5432"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
